### ISSUE TITLE
AVEC2013   dataset

### ISSUE THREAD

**Issue by xuxiuzhi2627** [chkche1/avec2013#1]
The complete avec2013 dataset is in the folder raw_features under the training folder?

**Comment by tzczsq** [comment]
Could you please send me the original AVEC2013 database? Now there is no public link for downloading this dataset.

**Comment by srinubevar** [comment]
if possible share the AVEC2013 original dataset now it is publicly not available.

**Comment by gjlmoon** [comment]
Could you please send me the original AVEC2013 database?

**Comment by HZIH** [comment]
Could you please send me the original AVEC2013 database? Now there is no public link for downloading this dataset.

**Comment by sharma-anshul** [comment]
Unfortunately we don't have the original dataset anymore. Closing this issue.

**Comment by Leanne-00** [comment]
Could you please send me the original AVEC2013 database? Now there is no public link for downloading this dataset.

**Comment by yuhuan-wu** [comment]
Hi guys, any news about this dataset?

**Comment by liyi-div** [comment]
Could you please send me the original AVEC2013 database? Now there is no public link for downloading this dataset.

**Comment by sharma-anshul** [comment]
Read the response above, this thread is closed.

**Comment by bhjkiki** [comment]
Could you please send me the original AVEC2013 database? Now there is no public link for downloading this dataset.
